import dynamic from "next/dynamic";
import Footer from "@/components/Footer";
import IPCard from "@/components/IPCard";
import Head from "next/head";
import { getDirection } from "@/lang/locale";
import { useState } from "react";
import IPContext, { IPContextType } from "@/store/IPContext";
import { AxiosResponse } from "axios";
import styles from '@/styles/Main.module.scss';

const Map = dynamic(
  () => {
    return import('@/components/Map');
  },
  { ssr: false }
);

export default function Home() {

  const [showMap, setShowMap] = useState(false);
  const [state, setState] = useState<IPContextType>({
    ip: "",
    subnet: "",
    city: "",
    country: "",
    latitude: 0,
    longitude: 0,
    asn: '',
    asn_org: '',
    hostname: '',
    user_agent: ''
  });

  const onIPReadyHandler = (ip: string) => {
    setState((prevState) => {
      return { ...prevState, ip: ip };
    });
  }

  const onIPInformationReadyHandler = (response: AxiosResponse<any, any>) => {
    setState((prevState) => {
      return {
        ...prevState,
        subnet: response.data.subnet,
        city: response.data.city,
        country: response.data.country,
        latitude: response.data.latitude,
        longitude: response.data.longitude,
        asn: response.data.asn,
        asn_org: response.data.asn_org,
        hostname: response.data.hostname,
        user_agent: response.data.user_agent
      };
    });
    setShowMap(true)
  }

  return (
    <IPContext.Provider value={state}>
      <Head>
        <title>JeoIP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicon/site.webmanifest" />
        <link
          rel="mask-icon"
          href="/favicon/safari-pinned-tab.svg"
          color="#5bbad5"
        />
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossOrigin=""
        />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <main dir={getDirection()} className={(getDirection() === 'rtl') ? styles['main__rtl'] : styles.main}>
        <Map className="d-none d-sm-block" lat={state.latitude} lng={state.longitude} fixed/>
        <IPCard onIPReady={onIPReadyHandler} onIPInformationReady={onIPInformationReadyHandler}/>
        <Footer />
      </main>
    </IPContext.Provider>
  );
}
